create table car (
	id INT PRIMARY KEY,
	make VARCHAR(50) NOT NULL,
	model VARCHAR(50) NOT NULL,
	, VARCHAR(50) NOT NULL,
	date NOW() NOT NULL
);
insert into car (id, make, model, ,) values (1, 'Chevrolet', 'Corvette', '$4.79');
insert into car (id, make, model, ,) values (2, 'Porsche', 'Cayenne', '$7.16');
insert into car (id, make, model, ,) values (3, 'Subaru', 'Tribeca', '$4.16');
insert into car (id, make, model, ,) values (4, 'Mazda', 'Tribute', '$6.73');
insert into car (id, make, model, ,) values (5, 'Scion', 'tC', '$6.09');
insert into car (id, make, model, ,) values (6, 'Pontiac', 'Aztek', '$6.75');
insert into car (id, make, model, ,) values (7, 'Plymouth', 'Breeze', '$1.67');
insert into car (id, make, model, ,) values (8, 'Mercury', 'Sable', '$6.31');
insert into car (id, make, model, ,) values (9, 'Lotus', 'Elise', '$5.53');
insert into car (id, make, model, ,) values (10, 'Mercedes-Benz', 'CLS-Class', '$3.05');
insert into car (id, make, model, ,) values (11, 'Mercury', 'Tracer', '$0.36');
insert into car (id, make, model, ,) values (12, 'Aston Martin', 'Vanquish S', '$9.47');
insert into car (id, make, model, ,) values (13, 'GMC', 'Yukon Denali', '$0.33');
insert into car (id, make, model, ,) values (14, 'Dodge', 'Stratus', '$4.87');
insert into car (id, make, model, ,) values (15, 'Chevrolet', 'Colorado', '$3.24');
insert into car (id, make, model, ,) values (16, 'Ford', 'Expedition', '$8.05');
insert into car (id, make, model, ,) values (17, 'Suzuki', 'Swift', '$0.30');
insert into car (id, make, model, ,) values (18, 'Volkswagen', 'GTI', '$9.00');
insert into car (id, make, model, ,) values (19, 'Mazda', 'B-Series', '$1.71');
insert into car (id, make, model, ,) values (20, 'Mercury', 'Monterey', '$6.57');
insert into car (id, make, model, ,) values (21, 'Porsche', 'Cayenne', '$4.56');
insert into car (id, make, model, ,) values (22, 'Mitsubishi', 'Starion', '$3.36');
insert into car (id, make, model, ,) values (23, 'BMW', '600', '$0.33');
insert into car (id, make, model, ,) values (24, 'BMW', 'M3', '$7.67');
insert into car (id, make, model, ,) values (25, 'Ford', 'Taurus', '$1.50');
insert into car (id, make, model, ,) values (26, 'Hyundai', 'Accent', '$6.90');
insert into car (id, make, model, ,) values (27, 'Chevrolet', 'Aveo', '$1.51');
insert into car (id, make, model, ,) values (28, 'Ford', 'Mustang', '$4.63');
insert into car (id, make, model, ,) values (29, 'Eagle', 'Vision', '$0.85');
insert into car (id, make, model, ,) values (30, 'BMW', '3 Series', '$8.13');
insert into car (id, make, model, ,) values (31, 'Nissan', 'Murano', '$0.19');
insert into car (id, make, model, ,) values (32, 'Mazda', 'CX-9', '$0.28');
insert into car (id, make, model, ,) values (33, 'Cadillac', 'Escalade EXT', '$6.67');
insert into car (id, make, model, ,) values (34, 'Chevrolet', 'Express 2500', '$6.74');
insert into car (id, make, model, ,) values (35, 'Volkswagen', 'Scirocco', '$6.83');
insert into car (id, make, model, ,) values (36, 'Audi', '100', '$3.43');
insert into car (id, make, model, ,) values (37, 'Chevrolet', 'Cobalt', '$7.24');
insert into car (id, make, model, ,) values (38, 'Nissan', 'Altima', '$0.64');
insert into car (id, make, model, ,) values (39, 'Ford', 'LTD Crown Victoria', '$0.79');
insert into car (id, make, model, ,) values (40, 'Land Rover', 'Defender 90', '$6.95');
insert into car (id, make, model, ,) values (41, 'Chrysler', 'Grand Voyager', '$2.02');
insert into car (id, make, model, ,) values (42, 'Chevrolet', 'Malibu', '$2.65');
insert into car (id, make, model, ,) values (43, 'GMC', 'Savana 3500', '$7.93');
insert into car (id, make, model, ,) values (44, 'Honda', 'Accord', '$3.27');
insert into car (id, make, model, ,) values (45, 'Chevrolet', 'Silverado 3500HD', '$8.47');
insert into car (id, make, model, ,) values (46, 'GMC', 'Envoy', '$7.79');
insert into car (id, make, model, ,) values (47, 'Mercedes-Benz', 'E-Class', '$6.99');
insert into car (id, make, model, ,) values (48, 'Porsche', '924 S', '$8.87');
insert into car (id, make, model, ,) values (49, 'Lotus', 'Exige', '$8.51');
insert into car (id, make, model, ,) values (50, 'Dodge', 'Stratus', '$5.67');
insert into car (id, make, model, ,) values (51, 'Kia', 'Carens', '$8.02');
insert into car (id, make, model, ,) values (52, 'Pontiac', 'Torrent', '$4.94');
insert into car (id, make, model, ,) values (53, 'Saturn', 'Aura', '$7.79');
insert into car (id, make, model, ,) values (54, 'Chevrolet', 'Suburban 1500', '$1.38');
insert into car (id, make, model, ,) values (55, 'Acura', 'Integra', '$5.64');
insert into car (id, make, model, ,) values (56, 'Volvo', '850', '$9.66');
insert into car (id, make, model, ,) values (57, 'Mercedes-Benz', 'E-Class', '$7.15');
insert into car (id, make, model, ,) values (58, 'Pontiac', 'Gemini', '$4.21');
insert into car (id, make, model, ,) values (59, 'Mitsubishi', 'Eclipse', '$5.71');
insert into car (id, make, model, ,) values (60, 'Volkswagen', 'Touareg', '$1.35');
insert into car (id, make, model, ,) values (61, 'Lincoln', 'MKS', '$0.93');
insert into car (id, make, model, ,) values (62, 'Ford', 'E350', '$1.10');
insert into car (id, make, model, ,) values (63, 'Volkswagen', 'GTI', '$4.96');
insert into car (id, make, model, ,) values (64, 'Ford', 'F-Series', '$4.78');
insert into car (id, make, model, ,) values (65, 'Chevrolet', 'Suburban 1500', '$6.67');
insert into car (id, make, model, ,) values (66, 'Mercury', 'Grand Marquis', '$3.14');
insert into car (id, make, model, ,) values (67, 'GMC', 'Savana 3500', '$9.79');
insert into car (id, make, model, ,) values (68, 'Mitsubishi', 'Outlander', '$4.60');
insert into car (id, make, model, ,) values (69, 'Oldsmobile', 'LSS', '$3.32');
insert into car (id, make, model, ,) values (70, 'Pontiac', 'Vibe', '$7.44');
insert into car (id, make, model, ,) values (71, 'Chevrolet', 'Tracker', '$8.64');
insert into car (id, make, model, ,) values (72, 'Infiniti', 'FX', '$0.80');
insert into car (id, make, model, ,) values (73, 'Chevrolet', 'Silverado 2500', '$9.73');
insert into car (id, make, model, ,) values (74, 'Nissan', 'Versa', '$8.87');
insert into car (id, make, model, ,) values (75, 'Saab', '900', '$8.74');
insert into car (id, make, model, ,) values (76, 'Mitsubishi', 'Pajero', '$5.83');
insert into car (id, make, model, ,) values (77, 'Audi', 'V8', '$2.73');
insert into car (id, make, model, ,) values (78, 'Mitsubishi', 'Space', '$1.52');
insert into car (id, make, model, ,) values (79, 'Plymouth', 'Grand Voyager', '$9.93');
insert into car (id, make, model, ,) values (80, 'Volkswagen', 'Touareg', '$9.68');
insert into car (id, make, model, ,) values (81, 'Dodge', 'Ram', '$5.30');
insert into car (id, make, model, ,) values (82, 'Toyota', 'Sequoia', '$2.01');
insert into car (id, make, model, ,) values (83, 'GMC', 'Canyon', '$8.00');
insert into car (id, make, model, ,) values (84, 'Kia', 'Amanti', '$7.85');
insert into car (id, make, model, ,) values (85, 'Honda', 'Prelude', '$4.25');
insert into car (id, make, model, ,) values (86, 'Ford', 'Focus', '$6.37');
insert into car (id, make, model, ,) values (87, 'Toyota', 'Tacoma', '$9.97');
insert into car (id, make, model, ,) values (88, 'Dodge', 'Stealth', '$6.79');
insert into car (id, make, model, ,) values (89, 'Audi', 'TT', '$7.21');
insert into car (id, make, model, ,) values (90, 'Jeep', 'Grand Cherokee', '$6.80');
insert into car (id, make, model, ,) values (91, 'Acura', 'CL', '$3.98');
insert into car (id, make, model, ,) values (92, 'Dodge', 'Stealth', '$1.45');
insert into car (id, make, model, ,) values (93, 'Lexus', 'ES', '$6.81');
insert into car (id, make, model, ,) values (94, 'Volkswagen', 'rio', '$5.87');
insert into car (id, make, model, ,) values (95, 'Chevrolet', 'Suburban 1500', '$7.37');
insert into car (id, make, model, ,) values (96, 'Holden', 'Monaro', '$0.26');
insert into car (id, make, model, ,) values (97, 'Ford', 'F150', '$8.31');
insert into car (id, make, model, ,) values (98, 'Suzuki', 'Kizashi', '$6.62');
insert into car (id, make, model, ,) values (99, 'Mazda', 'Tribute', '$1.40');
insert into car (id, make, model, ,) values (100, 'Kia', 'Rio5', '$0.57');
insert into car (id, make, model, ,) values (101, 'Plymouth', 'Grand Voyager', '$9.11');
insert into car (id, make, model, ,) values (102, 'Volvo', 'V70', '$7.16');
insert into car (id, make, model, ,) values (103, 'Ford', 'Edge', '$8.38');
insert into car (id, make, model, ,) values (104, 'Chevrolet', 'Monte Carlo', '$8.69');
insert into car (id, make, model, ,) values (105, 'GMC', 'Yukon XL 1500', '$3.70');
insert into car (id, make, model, ,) values (106, 'Porsche', 'Boxster', '$4.72');
insert into car (id, make, model, ,) values (107, 'Toyota', 'T100', '$0.25');
insert into car (id, make, model, ,) values (108, 'Lexus', 'LS', '$6.91');
insert into car (id, make, model, ,) values (109, 'Hyundai', 'Scoupe', '$7.50');
insert into car (id, make, model, ,) values (110, 'Chevrolet', 'Silverado', '$0.36');
insert into car (id, make, model, ,) values (111, 'Ford', 'E250', '$8.35');
insert into car (id, make, model, ,) values (112, 'Acura', 'CL', '$4.77');
insert into car (id, make, model, ,) values (113, 'Audi', 'Allroad', '$6.81');
insert into car (id, make, model, ,) values (114, 'Chevrolet', 'Suburban 2500', '$8.50');
insert into car (id, make, model, ,) values (115, 'Volvo', 'S70', '$5.62');
insert into car (id, make, model, ,) values (116, 'GMC', '3500', '$3.84');
insert into car (id, make, model, ,) values (117, 'Volvo', 'S60', '$4.42');
insert into car (id, make, model, ,) values (118, 'Ford', 'Ranger', '$3.63');
insert into car (id, make, model, ,) values (119, 'Chrysler', 'Imperial', '$4.19');
insert into car (id, make, model, ,) values (120, 'Honda', 'Accord', '$0.19');
insert into car (id, make, model, ,) values (121, 'GMC', '1500', '$5.65');
insert into car (id, make, model, ,) values (122, 'Porsche', '928', '$2.42');
insert into car (id, make, model, ,) values (123, 'Volvo', 'S80', '$0.35');
insert into car (id, make, model, ,) values (124, 'GMC', 'Sierra 1500', '$8.82');
insert into car (id, make, model, ,) values (125, 'Infiniti', 'QX56', '$8.14');
insert into car (id, make, model, ,) values (126, 'Ford', 'E-Series', '$2.02');
insert into car (id, make, model, ,) values (127, 'Acura', 'Vigor', '$3.12');
insert into car (id, make, model, ,) values (128, 'Chevrolet', 'Cobalt SS', '$2.89');
insert into car (id, make, model, ,) values (129, 'Saturn', 'Outlook', '$2.37');
insert into car (id, make, model, ,) values (130, 'Land Rover', 'Discovery', '$3.30');
insert into car (id, make, model, ,) values (131, 'Toyota', 'Camry', '$8.68');
insert into car (id, make, model, ,) values (132, 'GMC', 'Yukon', '$1.48');
insert into car (id, make, model, ,) values (133, 'Chevrolet', 'Express 1500', '$4.41');
insert into car (id, make, model, ,) values (134, 'BMW', 'X6', '$2.34');
insert into car (id, make, model, ,) values (135, 'Mitsubishi', 'Challenger', '$9.46');
insert into car (id, make, model, ,) values (136, 'Toyota', 'Avalon', '$4.85');
insert into car (id, make, model, ,) values (137, 'Honda', 'Accord', '$7.67');
insert into car (id, make, model, ,) values (138, 'BMW', 'X3', '$2.33');
insert into car (id, make, model, ,) values (139, 'Dodge', 'Ram Van 3500', '$2.84');
insert into car (id, make, model, ,) values (140, 'Mitsubishi', 'Montero', '$5.23');
insert into car (id, make, model, ,) values (141, 'Toyota', 'Tacoma', '$7.26');
insert into car (id, make, model, ,) values (142, 'Buick', 'Skyhawk', '$7.00');
insert into car (id, make, model, ,) values (143, 'Mercedes-Benz', 'C-Class', '$6.58');
insert into car (id, make, model, ,) values (144, 'Pontiac', 'Vibe', '$4.47');
insert into car (id, make, model, ,) values (145, 'Chevrolet', 'Malibu', '$8.55');
insert into car (id, make, model, ,) values (146, 'Ford', 'Probe', '$5.55');
insert into car (id, make, model, ,) values (147, 'Volvo', 'S40', '$8.04');
insert into car (id, make, model, ,) values (148, 'Pontiac', 'LeMans', '$1.52');
insert into car (id, make, model, ,) values (149, 'Lincoln', 'Mark VIII', '$8.33');
insert into car (id, make, model, ,) values (150, 'Audi', 'A5', '$4.33');
insert into car (id, make, model, ,) values (151, 'Honda', 'Element', '$0.58');
insert into car (id, make, model, ,) values (152, 'Nissan', 'Versa', '$6.73');
insert into car (id, make, model, ,) values (153, 'Maybach', '62', '$1.81');
insert into car (id, make, model, ,) values (154, 'Ford', 'Ranger', '$9.08');
insert into car (id, make, model, ,) values (155, 'Infiniti', 'G', '$6.72');
insert into car (id, make, model, ,) values (156, 'Chevrolet', 'Classic', '$9.36');
insert into car (id, make, model, ,) values (157, 'Mercedes-Benz', 'G-Class', '$8.51');
insert into car (id, make, model, ,) values (158, 'Ford', 'F-Series', '$4.04');
insert into car (id, make, model, ,) values (159, 'Mitsubishi', 'Endeavor', '$5.24');
insert into car (id, make, model, ,) values (160, 'Ford', 'F150', '$3.86');
insert into car (id, make, model, ,) values (161, 'GMC', 'Jimmy', '$3.44');
insert into car (id, make, model, ,) values (162, 'Subaru', 'Forester', '$3.57');
insert into car (id, make, model, ,) values (163, 'Volvo', 'S60', '$9.53');
insert into car (id, make, model, ,) values (164, 'Audi', 'Quattro', '$4.92');
insert into car (id, make, model, ,) values (165, 'Ford', 'EXP', '$7.59');
insert into car (id, make, model, ,) values (166, 'Mazda', '626', '$2.07');
insert into car (id, make, model, ,) values (167, 'GMC', 'Sonoma', '$7.05');
insert into car (id, make, model, ,) values (168, 'Ford', 'E-Series', '$8.19');
insert into car (id, make, model, ,) values (169, 'Hyundai', 'Sonata', '$4.23');
insert into car (id, make, model, ,) values (170, 'Rolls-Royce', 'Phantom', '$6.24');
insert into car (id, make, model, ,) values (171, 'Buick', 'Skylark', '$9.01');
insert into car (id, make, model, ,) values (172, 'Volkswagen', 'Jetta', '$9.09');
insert into car (id, make, model, ,) values (173, 'Infiniti', 'EX', '$1.49');
insert into car (id, make, model, ,) values (174, 'Chevrolet', 'Express 2500', '$3.63');
insert into car (id, make, model, ,) values (175, 'Audi', 'A3', '$8.83');
insert into car (id, make, model, ,) values (176, 'Dodge', 'Caravan', '$8.25');
insert into car (id, make, model, ,) values (177, 'Mercedes-Benz', 'SLS AMG', '$2.73');
insert into car (id, make, model, ,) values (178, 'Honda', 'Accord', '$2.82');
insert into car (id, make, model, ,) values (179, 'Chevrolet', 'Beretta', '$9.32');
insert into car (id, make, model, ,) values (180, 'Pontiac', 'Safari', '$1.03');
insert into car (id, make, model, ,) values (181, 'Buick', 'Century', '$7.79');
insert into car (id, make, model, ,) values (182, 'Toyota', 'T100', '$0.71');
insert into car (id, make, model, ,) values (183, 'Chevrolet', 'Corsica', '$9.75');
insert into car (id, make, model, ,) values (184, 'Lexus', 'ES', '$5.85');
insert into car (id, make, model, ,) values (185, 'Ford', 'Club Wagon', '$4.73');
insert into car (id, make, model, ,) values (186, 'Mercedes-Benz', 'S-Class', '$6.72');
insert into car (id, make, model, ,) values (187, 'Nissan', 'Versa', '$4.20');
insert into car (id, make, model, ,) values (188, 'GMC', 'Sierra 2500', '$2.79');
insert into car (id, make, model, ,) values (189, 'Mercury', 'Mystique', '$4.35');
insert into car (id, make, model, ,) values (190, 'Infiniti', 'QX', '$5.10');
insert into car (id, make, model, ,) values (191, 'Morgan', 'Aero 8', '$7.53');
insert into car (id, make, model, ,) values (192, 'Land Rover', 'Discovery', '$3.37');
insert into car (id, make, model, ,) values (193, 'Toyota', 'Prius', '$8.15');
insert into car (id, make, model, ,) values (194, 'Ford', 'Econoline E350', '$8.18');
insert into car (id, make, model, ,) values (195, 'Volkswagen', 'Scirocco', '$3.87');
insert into car (id, make, model, ,) values (196, 'Nissan', 'Pathfinder', '$0.66');
insert into car (id, make, model, ,) values (197, 'Mitsubishi', 'Montero Sport', '$1.00');
insert into car (id, make, model, ,) values (198, 'BMW', '3 Series', '$7.87');
insert into car (id, make, model, ,) values (199, 'Volkswagen', 'Golf', '$7.13');
insert into car (id, make, model, ,) values (200, 'Toyota', 'RAV4', '$0.88');
insert into car (id, make, model, ,) values (201, 'Subaru', 'Loyale', '$7.21');
insert into car (id, make, model, ,) values (202, 'Mercedes-Benz', 'CLS-Class', '$1.99');
insert into car (id, make, model, ,) values (203, 'Mitsubishi', 'Truck', '$8.07');
insert into car (id, make, model, ,) values (204, 'Ford', 'Taurus', '$6.35');
insert into car (id, make, model, ,) values (205, 'Maserati', 'GranSport', '$6.29');
insert into car (id, make, model, ,) values (206, 'Hummer', 'H1', '$2.88');
insert into car (id, make, model, ,) values (207, 'Ford', 'E250', '$6.35');
insert into car (id, make, model, ,) values (208, 'Mercury', 'Mariner', '$4.84');
insert into car (id, make, model, ,) values (209, 'Mitsubishi', 'Pajero', '$8.93');
insert into car (id, make, model, ,) values (210, 'Ford', 'Thunderbird', '$2.78');
insert into car (id, make, model, ,) values (211, 'GMC', '3500', '$3.61');
insert into car (id, make, model, ,) values (212, 'Mercedes-Benz', 'GL-Class', '$3.56');
insert into car (id, make, model, ,) values (213, 'Lincoln', 'Town Car', '$7.91');
insert into car (id, make, model, ,) values (214, 'Toyota', 'Land Cruiser', '$5.15');
insert into car (id, make, model, ,) values (215, 'Oldsmobile', 'Intrigue', '$2.65');
insert into car (id, make, model, ,) values (216, 'Ford', 'F250', '$4.37');
insert into car (id, make, model, ,) values (217, 'Chevrolet', 'Express 2500', '$7.32');
insert into car (id, make, model, ,) values (218, 'Acura', 'TSX', '$1.25');
insert into car (id, make, model, ,) values (219, 'Lincoln', 'Town Car', '$6.27');
insert into car (id, make, model, ,) values (220, 'Oldsmobile', 'Bravada', '$6.70');
insert into car (id, make, model, ,) values (221, 'Mercedes-Benz', 'SL-Class', '$2.93');
insert into car (id, make, model, ,) values (222, 'Toyota', 'RAV4', '$4.93');
insert into car (id, make, model, ,) values (223, 'Dodge', 'Ram 2500', '$4.82');
insert into car (id, make, model, ,) values (224, 'Suzuki', 'Aerio', '$4.06');
insert into car (id, make, model, ,) values (225, 'Jaguar', 'XK Series', '$1.77');
insert into car (id, make, model, ,) values (226, 'Cadillac', 'DTS', '$1.48');
insert into car (id, make, model, ,) values (227, 'Ford', 'F-Series', '$1.30');
insert into car (id, make, model, ,) values (228, 'Mitsubishi', 'Truck', '$5.50');
insert into car (id, make, model, ,) values (229, 'Ford', 'F450', '$7.53');
insert into car (id, make, model, ,) values (230, 'Plymouth', 'Colt', '$2.74');
insert into car (id, make, model, ,) values (231, 'Lincoln', 'Navigator', '$6.26');
insert into car (id, make, model, ,) values (232, 'Dodge', 'Viper', '$4.99');
insert into car (id, make, model, ,) values (233, 'Kia', 'Optima', '$3.68');
insert into car (id, make, model, ,) values (234, 'Chevrolet', 'Suburban 1500', '$0.09');
insert into car (id, make, model, ,) values (235, 'BMW', 'Z4', '$3.03');
insert into car (id, make, model, ,) values (236, 'Suzuki', 'Swift', '$8.87');
insert into car (id, make, model, ,) values (237, 'Dodge', 'Grand Caravan', '$9.20');
insert into car (id, make, model, ,) values (238, 'Pontiac', 'Vibe', '$7.06');
insert into car (id, make, model, ,) values (239, 'Lexus', 'ES', '$3.08');
insert into car (id, make, model, ,) values (240, 'Honda', 'FCX Clarity', '$3.58');
insert into car (id, make, model, ,) values (241, 'Ford', 'Explorer', '$0.75');
insert into car (id, make, model, ,) values (242, 'Pontiac', 'Torrent', '$0.25');
insert into car (id, make, model, ,) values (243, 'Maybach', '62', '$5.42');
insert into car (id, make, model, ,) values (244, 'Mazda', 'Mazda5', '$3.74');
insert into car (id, make, model, ,) values (245, 'Nissan', 'NX', '$6.68');
insert into car (id, make, model, ,) values (246, 'Chevrolet', 'Malibu', '$0.26');
insert into car (id, make, model, ,) values (247, 'GMC', 'Sierra 1500', '$3.43');
insert into car (id, make, model, ,) values (248, 'Infiniti', 'JX', '$6.08');
insert into car (id, make, model, ,) values (249, 'Land Rover', 'LR2', '$1.65');
insert into car (id, make, model, ,) values (250, 'Mercedes-Benz', 'S-Class', '$0.49');
insert into car (id, make, model, ,) values (251, 'Suzuki', 'Swift', '$2.57');
insert into car (id, make, model, ,) values (252, 'Kia', 'Sportage', '$4.76');
insert into car (id, make, model, ,) values (253, 'BMW', 'X3', '$1.12');
insert into car (id, make, model, ,) values (254, 'GMC', 'Vandura 2500', '$0.26');
insert into car (id, make, model, ,) values (255, 'Geo', 'Metro', '$6.80');
insert into car (id, make, model, ,) values (256, 'Plymouth', 'Neon', '$6.18');
insert into car (id, make, model, ,) values (257, 'Maserati', 'Quattroporte', '$3.96');
insert into car (id, make, model, ,) values (258, 'Chevrolet', 'Express 2500', '$9.08');
insert into car (id, make, model, ,) values (259, 'Honda', 'S2000', '$5.60');
insert into car (id, make, model, ,) values (260, 'Ford', 'F150', '$1.27');
insert into car (id, make, model, ,) values (261, 'Dodge', 'Viper', '$8.46');
insert into car (id, make, model, ,) values (262, 'Chevrolet', 'Blazer', '$2.36');
insert into car (id, make, model, ,) values (263, 'Suzuki', 'Grand Vitara', '$0.87');
insert into car (id, make, model, ,) values (264, 'Ford', 'Escort', '$9.06');
insert into car (id, make, model, ,) values (265, 'Mercedes-Benz', 'CLS-Class', '$4.19');
insert into car (id, make, model, ,) values (266, 'BMW', 'Z3', '$0.89');
insert into car (id, make, model, ,) values (267, 'Audi', 'Coupe Quattro', '$4.08');
insert into car (id, make, model, ,) values (268, 'Volkswagen', 'Golf', '$0.62');
insert into car (id, make, model, ,) values (269, 'Buick', 'Regal', '$2.09');
insert into car (id, make, model, ,) values (270, 'Honda', 'Element', '$7.58');
insert into car (id, make, model, ,) values (271, 'Cadillac', 'Seville', '$6.36');
insert into car (id, make, model, ,) values (272, 'Nissan', 'Pathfinder', '$6.69');
insert into car (id, make, model, ,) values (273, 'Mazda', 'MX-5', '$0.40');
insert into car (id, make, model, ,) values (274, 'Acura', 'Integra', '$8.11');
insert into car (id, make, model, ,) values (275, 'Mercedes-Benz', 'E-Class', '$7.25');
insert into car (id, make, model, ,) values (276, 'Toyota', 'Supra', '$1.15');
insert into car (id, make, model, ,) values (277, 'Subaru', 'Impreza', '$9.75');
insert into car (id, make, model, ,) values (278, 'GMC', 'Rally Wagon 3500', '$6.56');
insert into car (id, make, model, ,) values (279, 'Ford', 'LTD', '$1.64');
insert into car (id, make, model, ,) values (280, 'Buick', 'Skylark', '$8.81');
insert into car (id, make, model, ,) values (281, 'Jaguar', 'XJ Series', '$4.05');
insert into car (id, make, model, ,) values (282, 'Kia', 'Spectra', '$4.19');
insert into car (id, make, model, ,) values (283, 'Ford', 'Aerostar', '$4.34');
insert into car (id, make, model, ,) values (284, 'Oldsmobile', 'Silhouette', '$7.13');
insert into car (id, make, model, ,) values (285, 'Lotus', 'Esprit', '$2.49');
insert into car (id, make, model, ,) values (286, 'Buick', 'Riviera', '$5.45');
insert into car (id, make, model, ,) values (287, 'Mitsubishi', 'Eclipse', '$8.88');
insert into car (id, make, model, ,) values (288, 'Mitsubishi', 'Eclipse', '$8.81');
insert into car (id, make, model, ,) values (289, 'Mercedes-Benz', 'C-Class', '$2.99');
insert into car (id, make, model, ,) values (290, 'Acura', 'RL', '$0.43');
insert into car (id, make, model, ,) values (291, 'Ford', 'Bronco', '$9.83');
insert into car (id, make, model, ,) values (292, 'Scion', 'xD', '$6.89');
insert into car (id, make, model, ,) values (293, 'Porsche', 'Carrera GT', '$9.24');
insert into car (id, make, model, ,) values (294, 'Cadillac', 'Escalade', '$6.38');
insert into car (id, make, model, ,) values (295, 'Buick', 'Regal', '$5.58');
insert into car (id, make, model, ,) values (296, 'Nissan', 'Sentra', '$4.64');
insert into car (id, make, model, ,) values (297, 'Audi', 'A6', '$8.64');
insert into car (id, make, model, ,) values (298, 'Honda', 'Accord', '$7.68');
insert into car (id, make, model, ,) values (299, 'BMW', '5 Series', '$6.81');
insert into car (id, make, model, ,) values (300, 'Hyundai', 'Tiburon', '$1.30');
insert into car (id, make, model, ,) values (301, 'BMW', '5 Series', '$9.69');
insert into car (id, make, model, ,) values (302, 'Honda', 'CR-X', '$5.91');
insert into car (id, make, model, ,) values (303, 'Chevrolet', 'Corvette', '$2.02');
insert into car (id, make, model, ,) values (304, 'GMC', 'Yukon XL 1500', '$8.11');
insert into car (id, make, model, ,) values (305, 'Infiniti', 'G37', '$1.83');
insert into car (id, make, model, ,) values (306, 'Chevrolet', 'HHR', '$9.67');
insert into car (id, make, model, ,) values (307, 'Chevrolet', 'Venture', '$3.66');
insert into car (id, make, model, ,) values (308, 'Pontiac', 'Grand Prix', '$1.03');
insert into car (id, make, model, ,) values (309, 'GMC', 'Envoy XUV', '$3.60');
insert into car (id, make, model, ,) values (310, 'Toyota', 'Camry Solara', '$1.56');
insert into car (id, make, model, ,) values (311, 'Ford', 'Aerostar', '$0.83');
insert into car (id, make, model, ,) values (312, 'Volkswagen', 'R32', '$8.26');
insert into car (id, make, model, ,) values (313, 'Honda', 'Insight', '$4.12');
insert into car (id, make, model, ,) values (314, 'GMC', '3500', '$0.98');
insert into car (id, make, model, ,) values (315, 'MG', 'MGB', '$0.57');
insert into car (id, make, model, ,) values (316, 'Lincoln', 'MKX', '$4.20');
insert into car (id, make, model, ,) values (317, 'GMC', 'Sonoma', '$9.57');
insert into car (id, make, model, ,) values (318, 'Volkswagen', 'Passat', '$2.95');
insert into car (id, make, model, ,) values (319, 'Kia', 'Sedona', '$2.16');
insert into car (id, make, model, ,) values (320, 'Pontiac', 'Fiero', '$5.95');
insert into car (id, make, model, ,) values (321, 'Volkswagen', 'Golf', '$3.84');
insert into car (id, make, model, ,) values (322, 'Buick', 'Somerset', '$3.07');
insert into car (id, make, model, ,) values (323, 'Kia', 'Sedona', '$5.94');
insert into car (id, make, model, ,) values (324, 'Mitsubishi', 'Outlander', '$7.64');
insert into car (id, make, model, ,) values (325, 'Honda', 'Civic', '$2.25');
insert into car (id, make, model, ,) values (326, 'Mazda', 'MX-5', '$9.34');
insert into car (id, make, model, ,) values (327, 'Subaru', 'Justy', '$4.41');
insert into car (id, make, model, ,) values (328, 'Chrysler', 'Sebring', '$9.66');
insert into car (id, make, model, ,) values (329, 'Honda', 'Odyssey', '$9.49');
insert into car (id, make, model, ,) values (330, 'Audi', 'V8', '$4.33');
insert into car (id, make, model, ,) values (331, 'Buick', 'LeSabre', '$6.98');
insert into car (id, make, model, ,) values (332, 'Audi', 'A6', '$5.75');
insert into car (id, make, model, ,) values (333, 'Ford', 'Escort', '$4.92');
insert into car (id, make, model, ,) values (334, 'Ford', 'EXP', '$3.41');
insert into car (id, make, model, ,) values (335, 'Chrysler', 'PT Cruiser', '$7.83');
insert into car (id, make, model, ,) values (336, 'GMC', 'Vandura G2500', '$9.39');
insert into car (id, make, model, ,) values (337, 'Toyota', 'RAV4', '$0.40');
insert into car (id, make, model, ,) values (338, 'Corbin', 'Sparrow', '$2.65');
insert into car (id, make, model, ,) values (339, 'Volkswagen', 'GTI', '$6.06');
insert into car (id, make, model, ,) values (340, 'Ford', 'Five Hundred', '$5.36');
insert into car (id, make, model, ,) values (341, 'Eagle', 'Summit', '$8.96');
insert into car (id, make, model, ,) values (342, 'Volvo', 'C30', '$3.75');
insert into car (id, make, model, ,) values (343, 'Jeep', 'Patriot', '$0.28');
insert into car (id, make, model, ,) values (344, 'Hyundai', 'Santa Fe', '$4.96');
insert into car (id, make, model, ,) values (345, 'Ford', 'Econoline E150', '$6.79');
insert into car (id, make, model, ,) values (346, 'Audi', 'A8', '$2.73');
insert into car (id, make, model, ,) values (347, 'Ford', 'Thunderbird', '$1.57');
insert into car (id, make, model, ,) values (348, 'Pontiac', '6000', '$5.52');
insert into car (id, make, model, ,) values (349, 'Dodge', 'Caravan', '$6.66');
insert into car (id, make, model, ,) values (350, 'GMC', 'Yukon XL', '$5.32');
insert into car (id, make, model, ,) values (351, 'Toyota', 'Corolla', '$3.32');
insert into car (id, make, model, ,) values (352, 'Buick', 'Special', '$7.22');
insert into car (id, make, model, ,) values (353, 'Saturn', 'Outlook', '$1.44');
insert into car (id, make, model, ,) values (354, 'Lexus', 'ES', '$0.52');
insert into car (id, make, model, ,) values (355, 'Volkswagen', 'Scirocco', '$5.53');
insert into car (id, make, model, ,) values (356, 'Lexus', 'LS', '$0.53');
insert into car (id, make, model, ,) values (357, 'Infiniti', 'G25', '$2.16');
insert into car (id, make, model, ,) values (358, 'GMC', 'Vandura G3500', '$8.95');
insert into car (id, make, model, ,) values (359, 'Mercury', 'Capri', '$3.68');
insert into car (id, make, model, ,) values (360, 'Mercedes-Benz', 'W201', '$8.17');
insert into car (id, make, model, ,) values (361, 'Nissan', 'Frontier', '$7.34');
insert into car (id, make, model, ,) values (362, 'Dodge', 'Spirit', '$8.38');
insert into car (id, make, model, ,) values (363, 'Chrysler', 'New Yorker', '$6.22');
insert into car (id, make, model, ,) values (364, 'Ford', 'Freestar', '$1.51');
insert into car (id, make, model, ,) values (365, 'Infiniti', 'G', '$4.26');
insert into car (id, make, model, ,) values (366, 'Toyota', 'Matrix', '$3.80');
insert into car (id, make, model, ,) values (367, 'Toyota', 'Tundra', '$3.40');
insert into car (id, make, model, ,) values (368, 'Volkswagen', 'Jetta', '$2.90');
insert into car (id, make, model, ,) values (369, 'Land Rover', 'Discovery', '$7.08');
insert into car (id, make, model, ,) values (370, 'Plymouth', 'Prowler', '$9.37');
insert into car (id, make, model, ,) values (371, 'Cadillac', 'CTS', '$0.17');
insert into car (id, make, model, ,) values (372, 'Subaru', 'Justy', '$7.52');
insert into car (id, make, model, ,) values (373, 'Chevrolet', 'Express 2500', '$2.24');
insert into car (id, make, model, ,) values (374, 'Saab', '9-5', '$8.30');
insert into car (id, make, model, ,) values (375, 'Dodge', 'Ram 1500', '$3.04');
insert into car (id, make, model, ,) values (376, 'Mitsubishi', 'Expo', '$5.19');
insert into car (id, make, model, ,) values (377, 'Volkswagen', 'Cabriolet', '$7.68');
insert into car (id, make, model, ,) values (378, 'Mitsubishi', 'Diamante', '$5.31');
insert into car (id, make, model, ,) values (379, 'Audi', '90', '$3.44');
insert into car (id, make, model, ,) values (380, 'Pontiac', 'LeMans', '$6.70');
insert into car (id, make, model, ,) values (381, 'Chevrolet', 'Caprice Classic', '$3.69');
insert into car (id, make, model, ,) values (382, 'Mazda', 'MX-6', '$4.88');
insert into car (id, make, model, ,) values (383, 'GMC', 'Savana 2500', '$8.05');
insert into car (id, make, model, ,) values (384, 'BMW', '3 Series', '$3.72');
insert into car (id, make, model, ,) values (385, 'BMW', '8 Series', '$7.49');
insert into car (id, make, model, ,) values (386, 'GMC', 'Savana 1500', '$0.77');
insert into car (id, make, model, ,) values (387, 'Mercedes-Benz', 'C-Class', '$0.45');
insert into car (id, make, model, ,) values (388, 'Chevrolet', 'Silverado', '$3.72');
insert into car (id, make, model, ,) values (389, 'Geo', 'Tracker', '$9.87');
insert into car (id, make, model, ,) values (390, 'Toyota', 'Matrix', '$4.56');
insert into car (id, make, model, ,) values (391, 'Ford', 'GT500', '$4.45');
insert into car (id, make, model, ,) values (392, 'Suzuki', 'XL7', '$6.01');
insert into car (id, make, model, ,) values (393, 'Oldsmobile', '98', '$0.01');
insert into car (id, make, model, ,) values (394, 'Chrysler', '200', '$0.16');
insert into car (id, make, model, ,) values (395, 'Subaru', 'XT', '$8.24');
insert into car (id, make, model, ,) values (396, 'Nissan', 'Maxima', '$2.48');
insert into car (id, make, model, ,) values (397, 'Mercedes-Benz', 'CL-Class', '$7.69');
insert into car (id, make, model, ,) values (398, 'Ford', 'Tempo', '$1.13');
insert into car (id, make, model, ,) values (399, 'Dodge', 'Viper', '$9.26');
insert into car (id, make, model, ,) values (400, 'Chevrolet', 'Tracker', '$0.80');
insert into car (id, make, model, ,) values (401, 'Ferrari', '599 GTB Fiorano', '$0.85');
insert into car (id, make, model, ,) values (402, 'Ford', 'Expedition', '$0.66');
insert into car (id, make, model, ,) values (403, 'Volvo', '960', '$7.90');
insert into car (id, make, model, ,) values (404, 'Saturn', 'Astra', '$0.23');
insert into car (id, make, model, ,) values (405, 'Ford', 'Escort', '$5.46');
insert into car (id, make, model, ,) values (406, 'Infiniti', 'QX56', '$1.84');
insert into car (id, make, model, ,) values (407, 'Mitsubishi', 'Pajero', '$1.37');
insert into car (id, make, model, ,) values (408, 'Lincoln', 'MKT', '$0.62');
insert into car (id, make, model, ,) values (409, 'Volvo', 'S80', '$1.35');
insert into car (id, make, model, ,) values (410, 'Honda', 'Odyssey', '$0.05');
insert into car (id, make, model, ,) values (411, 'Subaru', 'Legacy', '$5.22');
insert into car (id, make, model, ,) values (412, 'Toyota', 'Solara', '$5.89');
insert into car (id, make, model, ,) values (413, 'Chevrolet', 'Cobalt SS', '$0.98');
insert into car (id, make, model, ,) values (414, 'Porsche', '928', '$4.51');
insert into car (id, make, model, ,) values (415, 'Suzuki', 'Reno', '$6.91');
insert into car (id, make, model, ,) values (416, 'Maybach', '57', '$5.67');
insert into car (id, make, model, ,) values (417, 'GMC', 'Jimmy', '$8.33');
insert into car (id, make, model, ,) values (418, 'Infiniti', 'QX', '$8.29');
insert into car (id, make, model, ,) values (419, 'Audi', '4000CS Quattro', '$6.55');
insert into car (id, make, model, ,) values (420, 'Ford', 'F250', '$5.68');
insert into car (id, make, model, ,) values (421, 'Isuzu', 'VehiCROSS', '$8.22');
insert into car (id, make, model, ,) values (422, 'Citroën', 'CX', '$2.89');
insert into car (id, make, model, ,) values (423, 'Volvo', '940', '$0.81');
insert into car (id, make, model, ,) values (424, 'Isuzu', 'Amigo', '$3.05');
insert into car (id, make, model, ,) values (425, 'Ford', 'Club Wagon', '$3.04');
insert into car (id, make, model, ,) values (426, 'Nissan', 'Xterra', '$6.00');
insert into car (id, make, model, ,) values (427, 'Mazda', 'Protege', '$3.11');
insert into car (id, make, model, ,) values (428, 'Dodge', 'Ram 2500', '$0.30');
insert into car (id, make, model, ,) values (429, 'Mitsubishi', 'GTO', '$2.53');
insert into car (id, make, model, ,) values (430, 'Chrysler', '300', '$2.09');
insert into car (id, make, model, ,) values (431, 'Ford', 'Ranger', '$4.59');
insert into car (id, make, model, ,) values (432, 'Chevrolet', 'G-Series 1500', '$3.44');
insert into car (id, make, model, ,) values (433, 'Mercedes-Benz', 'R-Class', '$2.97');
insert into car (id, make, model, ,) values (434, 'Mercedes-Benz', 'W201', '$5.75');
insert into car (id, make, model, ,) values (435, 'Ford', 'Fiesta', '$9.47');
insert into car (id, make, model, ,) values (436, 'Corbin', 'Sparrow', '$2.68');
insert into car (id, make, model, ,) values (437, 'Ford', 'Tempo', '$5.21');
insert into car (id, make, model, ,) values (438, 'Toyota', '4Runner', '$5.27');
insert into car (id, make, model, ,) values (439, 'Infiniti', 'G', '$9.72');
insert into car (id, make, model, ,) values (440, 'Pontiac', 'GTO', '$4.79');
insert into car (id, make, model, ,) values (441, 'Ford', 'Fusion', '$7.13');
insert into car (id, make, model, ,) values (442, 'Audi', '5000CS', '$2.78');
insert into car (id, make, model, ,) values (443, 'Scion', 'tC', '$1.79');
insert into car (id, make, model, ,) values (444, 'Land Rover', 'Discovery', '$1.38');
insert into car (id, make, model, ,) values (445, 'Volkswagen', 'GTI', '$0.24');
insert into car (id, make, model, ,) values (446, 'Cadillac', 'XLR', '$7.46');
insert into car (id, make, model, ,) values (447, 'Honda', 'Civic', '$0.21');
insert into car (id, make, model, ,) values (448, 'Studebaker', 'Avanti', '$9.69');
insert into car (id, make, model, ,) values (449, 'Mitsubishi', 'Lancer', '$8.27');
insert into car (id, make, model, ,) values (450, 'Ford', 'Contour', '$7.17');
insert into car (id, make, model, ,) values (451, 'Chevrolet', 'Cobalt', '$7.99');
insert into car (id, make, model, ,) values (452, 'Toyota', 'Yaris', '$3.85');
insert into car (id, make, model, ,) values (453, 'Saab', '9000', '$9.06');
insert into car (id, make, model, ,) values (454, 'BMW', '5 Series', '$9.82');
insert into car (id, make, model, ,) values (455, 'Pontiac', 'Grand Am', '$0.11');
insert into car (id, make, model, ,) values (456, 'Plymouth', 'Laser', '$1.40');
insert into car (id, make, model, ,) values (457, 'GMC', 'Sierra 2500', '$3.47');
insert into car (id, make, model, ,) values (458, 'Toyota', 'Land Cruiser', '$7.97');
insert into car (id, make, model, ,) values (459, 'Buick', 'Park Avenue', '$6.40');
insert into car (id, make, model, ,) values (460, 'Lexus', 'GS', '$1.04');
insert into car (id, make, model, ,) values (461, 'Chevrolet', 'Silverado 1500', '$1.98');
insert into car (id, make, model, ,) values (462, 'Toyota', 'Tacoma', '$4.12');
insert into car (id, make, model, ,) values (463, 'Mazda', 'MPV', '$4.44');
insert into car (id, make, model, ,) values (464, 'Lexus', 'GX', '$8.66');
insert into car (id, make, model, ,) values (465, 'Subaru', 'Outback', '$7.86');
insert into car (id, make, model, ,) values (466, 'Mercedes-Benz', 'SLR McLaren', '$0.51');
insert into car (id, make, model, ,) values (467, 'Nissan', 'Xterra', '$6.64');
insert into car (id, make, model, ,) values (468, 'Hyundai', 'Elantra', '$4.05');
insert into car (id, make, model, ,) values (469, 'Jaguar', 'XF', '$7.52');
insert into car (id, make, model, ,) values (470, 'Mitsubishi', 'L300', '$6.06');
insert into car (id, make, model, ,) values (471, 'Chevrolet', 'Colorado', '$1.91');
insert into car (id, make, model, ,) values (472, 'Subaru', 'Outback', '$0.78');
insert into car (id, make, model, ,) values (473, 'Kia', 'Sportage', '$7.86');
insert into car (id, make, model, ,) values (474, 'Ford', 'Th!nk', '$2.68');
insert into car (id, make, model, ,) values (475, 'Audi', 'S4', '$2.50');
insert into car (id, make, model, ,) values (476, 'Subaru', 'Justy', '$0.36');
insert into car (id, make, model, ,) values (477, 'Hummer', 'H1', '$9.29');
insert into car (id, make, model, ,) values (478, 'Dodge', 'Charger', '$2.20');
insert into car (id, make, model, ,) values (479, 'Mazda', 'MX-5', '$8.05');
insert into car (id, make, model, ,) values (480, 'Chevrolet', 'APV', '$1.65');
insert into car (id, make, model, ,) values (481, 'BMW', '5 Series', '$5.14');
insert into car (id, make, model, ,) values (482, 'Land Rover', 'Freelander', '$5.38');
insert into car (id, make, model, ,) values (483, 'Hummer', 'H3', '$1.48');
insert into car (id, make, model, ,) values (484, 'Ford', 'Ranger', '$8.96');
insert into car (id, make, model, ,) values (485, 'Mitsubishi', 'Eclipse', '$9.88');
insert into car (id, make, model, ,) values (486, 'Mitsubishi', 'Chariot', '$8.98');
insert into car (id, make, model, ,) values (487, 'Chevrolet', '2500', '$8.89');
insert into car (id, make, model, ,) values (488, 'Chrysler', 'Crossfire', '$6.99');
insert into car (id, make, model, ,) values (489, 'Ford', 'Bronco II', '$9.18');
insert into car (id, make, model, ,) values (490, 'Chevrolet', 'Tahoe', '$0.65');
insert into car (id, make, model, ,) values (491, 'Mazda', 'MX-3', '$1.21');
insert into car (id, make, model, ,) values (492, 'Oldsmobile', 'LSS', '$7.08');
insert into car (id, make, model, ,) values (493, 'Jeep', 'Liberty', '$2.56');
insert into car (id, make, model, ,) values (494, 'Pontiac', 'GTO', '$3.96');
insert into car (id, make, model, ,) values (495, 'Suzuki', 'Swift', '$0.46');
insert into car (id, make, model, ,) values (496, 'Panoz', 'Esperante', '$0.99');
insert into car (id, make, model, ,) values (497, 'Jeep', 'Grand Cherokee', '$8.75');
insert into car (id, make, model, ,) values (498, 'Dodge', 'Dakota Club', '$6.32');
insert into car (id, make, model, ,) values (499, 'Chevrolet', 'Corvette', '$2.51');
insert into car (id, make, model, ,) values (500, 'Pontiac', 'Bonneville', '$10.00');
insert into car (id, make, model, ,) values (501, 'Land Rover', 'Discovery', '$8.39');
insert into car (id, make, model, ,) values (502, 'Saturn', 'VUE', '$6.89');
insert into car (id, make, model, ,) values (503, 'Mazda', 'B-Series Plus', '$4.76');
insert into car (id, make, model, ,) values (504, 'Mercedes-Benz', 'M-Class', '$2.08');
insert into car (id, make, model, ,) values (505, 'Audi', 'RS 4', '$5.45');
insert into car (id, make, model, ,) values (506, 'Chrysler', 'Cirrus', '$4.88');
insert into car (id, make, model, ,) values (507, 'Mercedes-Benz', 'CLS-Class', '$5.79');
insert into car (id, make, model, ,) values (508, 'Mazda', 'CX-9', '$0.51');
insert into car (id, make, model, ,) values (509, 'Ford', 'Expedition', '$1.61');
insert into car (id, make, model, ,) values (510, 'Mitsubishi', 'Pajero', '$8.78');
insert into car (id, make, model, ,) values (511, 'Pontiac', 'Trans Sport', '$3.47');
insert into car (id, make, model, ,) values (512, 'Honda', 'Prelude', '$6.64');
insert into car (id, make, model, ,) values (513, 'Toyota', 'Avalon', '$7.18');
insert into car (id, make, model, ,) values (514, 'Lamborghini', 'Murciélago', '$5.47');
insert into car (id, make, model, ,) values (515, 'Chevrolet', 'Suburban', '$0.06');
insert into car (id, make, model, ,) values (516, 'Chevrolet', 'Suburban 1500', '$8.95');
insert into car (id, make, model, ,) values (517, 'Ford', 'Thunderbird', '$5.23');
insert into car (id, make, model, ,) values (518, 'Pontiac', 'Tempest', '$0.90');
insert into car (id, make, model, ,) values (519, 'Mercedes-Benz', 'M-Class', '$8.93');
insert into car (id, make, model, ,) values (520, 'Dodge', 'Dakota', '$2.10');
insert into car (id, make, model, ,) values (521, 'Lotus', 'Esprit', '$2.31');
insert into car (id, make, model, ,) values (522, 'Mitsubishi', '3000GT', '$8.90');
insert into car (id, make, model, ,) values (523, 'Ford', 'F-Series', '$1.09');
insert into car (id, make, model, ,) values (524, 'Subaru', 'XT', '$7.91');
insert into car (id, make, model, ,) values (525, 'BMW', 'M3', '$2.95');
insert into car (id, make, model, ,) values (526, 'Honda', 'Passport', '$7.78');
insert into car (id, make, model, ,) values (527, 'Volkswagen', 'Cabriolet', '$2.50');
insert into car (id, make, model, ,) values (528, 'Chrysler', '200', '$6.83');
insert into car (id, make, model, ,) values (529, 'Volvo', 'V70', '$8.51');
insert into car (id, make, model, ,) values (530, 'Mercedes-Benz', 'S-Class', '$9.42');
insert into car (id, make, model, ,) values (531, 'Mitsubishi', 'Lancer', '$7.41');
insert into car (id, make, model, ,) values (532, 'Pontiac', 'Bonneville', '$6.63');
insert into car (id, make, model, ,) values (533, 'Ford', 'F250', '$9.35');
insert into car (id, make, model, ,) values (534, 'Dodge', 'Ram 3500', '$2.27');
insert into car (id, make, model, ,) values (535, 'Saturn', 'S-Series', '$8.23');
insert into car (id, make, model, ,) values (536, 'Saab', '900', '$8.97');
insert into car (id, make, model, ,) values (537, 'Dodge', 'Ram Van B350', '$8.26');
insert into car (id, make, model, ,) values (538, 'Nissan', 'Altima', '$2.25');
insert into car (id, make, model, ,) values (539, 'Lincoln', 'Navigator L', '$7.14');
insert into car (id, make, model, ,) values (540, 'Volkswagen', 'Jetta', '$9.33');
insert into car (id, make, model, ,) values (541, 'Dodge', 'Durango', '$3.34');
insert into car (id, make, model, ,) values (542, 'Lincoln', 'Mark LT', '$7.87');
insert into car (id, make, model, ,) values (543, 'Pontiac', 'Grand Prix', '$0.96');
insert into car (id, make, model, ,) values (544, 'Honda', 'Insight', '$7.81');
insert into car (id, make, model, ,) values (545, 'Ford', 'Expedition EL', '$5.06');
insert into car (id, make, model, ,) values (546, 'Toyota', 'Tacoma Xtra', '$0.41');
insert into car (id, make, model, ,) values (547, 'Infiniti', 'QX', '$2.42');
insert into car (id, make, model, ,) values (548, 'Ford', 'Mustang', '$9.93');
insert into car (id, make, model, ,) values (549, 'Ford', 'Flex', '$2.49');
insert into car (id, make, model, ,) values (550, 'Mazda', 'RX-7', '$0.82');
insert into car (id, make, model, ,) values (551, 'Buick', 'Regal', '$4.82');
insert into car (id, make, model, ,) values (552, 'Lincoln', 'Navigator', '$6.76');
insert into car (id, make, model, ,) values (553, 'BMW', '5 Series', '$1.31');
insert into car (id, make, model, ,) values (554, 'Ford', 'Explorer', '$6.44');
insert into car (id, make, model, ,) values (555, 'Mitsubishi', 'Mirage', '$5.50');
insert into car (id, make, model, ,) values (556, 'Audi', 'S4', '$6.32');
insert into car (id, make, model, ,) values (557, 'Chevrolet', 'Tracker', '$7.12');
insert into car (id, make, model, ,) values (558, 'Rambler', 'Classic', '$2.85');
insert into car (id, make, model, ,) values (559, 'Mazda', 'Familia', '$5.74');
insert into car (id, make, model, ,) values (560, 'Ford', 'F350', '$3.24');
insert into car (id, make, model, ,) values (561, 'Mazda', 'MX-5', '$9.81');
insert into car (id, make, model, ,) values (562, 'Buick', 'LeSabre', '$1.67');
insert into car (id, make, model, ,) values (563, 'Jaguar', 'S-Type', '$5.39');
insert into car (id, make, model, ,) values (564, 'Maybach', 'Landaulet', '$1.22');
insert into car (id, make, model, ,) values (565, 'Nissan', 'Titan', '$6.11');
insert into car (id, make, model, ,) values (566, 'Mitsubishi', 'Diamante', '$3.34');
insert into car (id, make, model, ,) values (567, 'Buick', 'Terraza', '$3.96');
insert into car (id, make, model, ,) values (568, 'Toyota', 'Celica', '$1.47');
insert into car (id, make, model, ,) values (569, 'Jeep', 'Liberty', '$2.77');
insert into car (id, make, model, ,) values (570, 'Mitsubishi', 'Montero', '$7.69');
insert into car (id, make, model, ,) values (571, 'Ford', 'Laser', '$2.97');
insert into car (id, make, model, ,) values (572, 'Dodge', 'Ram 2500', '$0.56');
insert into car (id, make, model, ,) values (573, 'Mitsubishi', 'Endeavor', '$0.85');
insert into car (id, make, model, ,) values (574, 'Ford', 'E-Series', '$9.26');
insert into car (id, make, model, ,) values (575, 'Chrysler', 'Crossfire', '$6.44');
insert into car (id, make, model, ,) values (576, 'Aston Martin', 'V8 Vantage', '$1.91');
insert into car (id, make, model, ,) values (577, 'Ford', 'Freestyle', '$3.94');
insert into car (id, make, model, ,) values (578, 'Pontiac', 'Firebird', '$9.90');
insert into car (id, make, model, ,) values (579, 'Chrysler', '300M', '$8.27');
insert into car (id, make, model, ,) values (580, 'Volkswagen', 'Jetta', '$8.60');
insert into car (id, make, model, ,) values (581, 'Toyota', 'Camry Hybrid', '$1.56');
insert into car (id, make, model, ,) values (582, 'Subaru', 'SVX', '$4.72');
insert into car (id, make, model, ,) values (583, 'Chevrolet', 'Colorado', '$2.93');
insert into car (id, make, model, ,) values (584, 'Toyota', 'Sienna', '$8.98');
insert into car (id, make, model, ,) values (585, 'Dodge', 'Caravan', '$3.15');
insert into car (id, make, model, ,) values (586, 'Audi', 'A4', '$9.10');
insert into car (id, make, model, ,) values (587, 'Ford', 'E-Series', '$4.49');
insert into car (id, make, model, ,) values (588, 'Jeep', 'Wrangler', '$7.90');
insert into car (id, make, model, ,) values (589, 'Dodge', 'Stratus', '$1.82');
insert into car (id, make, model, ,) values (590, 'Mazda', 'Miata MX-5', '$1.52');
insert into car (id, make, model, ,) values (591, 'Chevrolet', 'Astro', '$9.09');
insert into car (id, make, model, ,) values (592, 'Hyundai', 'Tiburon', '$4.94');
insert into car (id, make, model, ,) values (593, 'Toyota', 'RAV4', '$1.30');
insert into car (id, make, model, ,) values (594, 'Volkswagen', 'Cabriolet', '$0.93');
insert into car (id, make, model, ,) values (595, 'Jeep', 'Wrangler', '$7.43');
insert into car (id, make, model, ,) values (596, 'Ferrari', '612 Scaglietti', '$3.21');
insert into car (id, make, model, ,) values (597, 'Chevrolet', 'Suburban 1500', '$5.37');
insert into car (id, make, model, ,) values (598, 'Lincoln', 'Continental', '$4.89');
insert into car (id, make, model, ,) values (599, 'Plymouth', 'Grand Voyager', '$4.10');
insert into car (id, make, model, ,) values (600, 'Chevrolet', 'Corvette', '$7.86');
insert into car (id, make, model, ,) values (601, 'Infiniti', 'QX', '$1.25');
insert into car (id, make, model, ,) values (602, 'BMW', 'X5', '$9.65');
insert into car (id, make, model, ,) values (603, 'Mercedes-Benz', 'E-Class', '$2.97');
insert into car (id, make, model, ,) values (604, 'Pontiac', 'LeMans', '$3.18');
insert into car (id, make, model, ,) values (605, 'Infiniti', 'G', '$8.22');
insert into car (id, make, model, ,) values (606, 'BMW', 'Z4', '$1.26');
insert into car (id, make, model, ,) values (607, 'Plymouth', 'Grand Voyager', '$2.65');
insert into car (id, make, model, ,) values (608, 'Bentley', 'Continental GTC', '$7.43');
insert into car (id, make, model, ,) values (609, 'Mazda', 'B-Series', '$8.28');
insert into car (id, make, model, ,) values (610, 'Saab', '9-3', '$6.45');
insert into car (id, make, model, ,) values (611, 'Toyota', 'Xtra', '$6.44');
insert into car (id, make, model, ,) values (612, 'Ford', 'Econoline E250', '$7.09');
insert into car (id, make, model, ,) values (613, 'Plymouth', 'Roadrunner', '$9.02');
insert into car (id, make, model, ,) values (614, 'Dodge', 'Ram 2500', '$7.15');
insert into car (id, make, model, ,) values (615, 'Plymouth', 'Colt Vista', '$5.56');
insert into car (id, make, model, ,) values (616, 'Chrysler', 'PT Cruiser', '$1.68');
insert into car (id, make, model, ,) values (617, 'Oldsmobile', 'Silhouette', '$1.32');
insert into car (id, make, model, ,) values (618, 'Toyota', '4Runner', '$0.50');
insert into car (id, make, model, ,) values (619, 'Nissan', 'Versa', '$5.19');
insert into car (id, make, model, ,) values (620, 'Ford', 'F350', '$1.34');
insert into car (id, make, model, ,) values (621, 'Ford', 'Festiva', '$0.57');
insert into car (id, make, model, ,) values (622, 'Toyota', 'Corolla', '$6.77');
insert into car (id, make, model, ,) values (623, 'Pontiac', 'Bonneville', '$7.42');
insert into car (id, make, model, ,) values (624, 'Lexus', 'RX Hybrid', '$8.43');
insert into car (id, make, model, ,) values (625, 'Hillman', 'Minx Magnificent', '$7.69');
insert into car (id, make, model, ,) values (626, 'Land Rover', 'Range Rover', '$4.01');
insert into car (id, make, model, ,) values (627, 'Lotus', 'Exige', '$1.84');
insert into car (id, make, model, ,) values (628, 'Mazda', '323', '$8.21');
insert into car (id, make, model, ,) values (629, 'Chevrolet', 'Tahoe', '$9.75');
insert into car (id, make, model, ,) values (630, 'Chevrolet', 'Cobalt', '$2.39');
insert into car (id, make, model, ,) values (631, 'Infiniti', 'Q', '$8.78');
insert into car (id, make, model, ,) values (632, 'Chevrolet', 'Aveo', '$2.32');
insert into car (id, make, model, ,) values (633, 'Ford', 'E-Series', '$1.51');
insert into car (id, make, model, ,) values (634, 'GMC', 'Savana 2500', '$1.83');
insert into car (id, make, model, ,) values (635, 'GMC', 'Savana 1500', '$3.73');
insert into car (id, make, model, ,) values (636, 'Lincoln', 'Town Car', '$9.25');
insert into car (id, make, model, ,) values (637, 'Nissan', 'NV3500', '$6.63');
insert into car (id, make, model, ,) values (638, 'Nissan', 'Altima', '$4.59');
insert into car (id, make, model, ,) values (639, 'Jeep', 'Commander', '$7.73');
insert into car (id, make, model, ,) values (640, 'GMC', 'Sonoma', '$2.92');
insert into car (id, make, model, ,) values (641, 'Mitsubishi', 'Galant', '$2.45');
insert into car (id, make, model, ,) values (642, 'Mercedes-Benz', 'SLK-Class', '$1.92');
insert into car (id, make, model, ,) values (643, 'Lotus', 'Elise', '$2.52');
insert into car (id, make, model, ,) values (644, 'Mercedes-Benz', '300D', '$4.75');
insert into car (id, make, model, ,) values (645, 'GMC', 'Sierra Hybrid', '$3.08');
insert into car (id, make, model, ,) values (646, 'Honda', 'CR-V', '$8.02');
insert into car (id, make, model, ,) values (647, 'Toyota', 'Xtra', '$9.94');
insert into car (id, make, model, ,) values (648, 'Buick', 'Century', '$7.23');
insert into car (id, make, model, ,) values (649, 'GMC', 'Sierra 2500', '$6.99');
insert into car (id, make, model, ,) values (650, 'Volkswagen', 'Jetta', '$3.77');
insert into car (id, make, model, ,) values (651, 'Nissan', 'Maxima', '$1.35');
insert into car (id, make, model, ,) values (652, 'Lamborghini', 'Gallardo', '$6.87');
insert into car (id, make, model, ,) values (653, 'Buick', 'Regal', '$8.26');
insert into car (id, make, model, ,) values (654, 'Pontiac', 'Firefly', '$0.08');
insert into car (id, make, model, ,) values (655, 'Lexus', 'LS', '$6.68');
insert into car (id, make, model, ,) values (656, 'Ford', 'Aerostar', '$9.21');
insert into car (id, make, model, ,) values (657, 'Mercedes-Benz', 'E-Class', '$2.23');
insert into car (id, make, model, ,) values (658, 'Mazda', 'MX-6', '$3.88');
insert into car (id, make, model, ,) values (659, 'Ford', 'E150', '$1.61');
insert into car (id, make, model, ,) values (660, 'Nissan', 'Quest', '$2.83');
insert into car (id, make, model, ,) values (661, 'Lexus', 'GS', '$9.30');
insert into car (id, make, model, ,) values (662, 'Mazda', 'Familia', '$0.40');
insert into car (id, make, model, ,) values (663, 'Ford', 'Transit Connect', '$9.06');
insert into car (id, make, model, ,) values (664, 'BMW', '6 Series', '$7.88');
insert into car (id, make, model, ,) values (665, 'Mitsubishi', 'Eclipse', '$6.36');
insert into car (id, make, model, ,) values (666, 'Chevrolet', 'Cobalt', '$8.23');
insert into car (id, make, model, ,) values (667, 'BMW', 'X6 M', '$8.84');
insert into car (id, make, model, ,) values (668, 'Plymouth', 'Fury', '$1.20');
insert into car (id, make, model, ,) values (669, 'Mercedes-Benz', 'C-Class', '$9.88');
insert into car (id, make, model, ,) values (670, 'Mercury', 'Grand Marquis', '$2.57');
insert into car (id, make, model, ,) values (671, 'Lexus', 'ES', '$0.74');
insert into car (id, make, model, ,) values (672, 'Jeep', 'Grand Cherokee', '$8.54');
insert into car (id, make, model, ,) values (673, 'Ford', 'F-Series', '$1.39');
insert into car (id, make, model, ,) values (674, 'Volkswagen', 'Tiguan', '$1.29');
insert into car (id, make, model, ,) values (675, 'Lexus', 'SC', '$2.12');
insert into car (id, make, model, ,) values (676, 'Porsche', 'Cayenne', '$7.26');
insert into car (id, make, model, ,) values (677, 'Pontiac', 'Gemini', '$3.60');
insert into car (id, make, model, ,) values (678, 'Isuzu', 'i-290', '$2.87');
insert into car (id, make, model, ,) values (679, 'Volvo', 'C70', '$4.77');
insert into car (id, make, model, ,) values (680, 'Toyota', 'Highlander', '$6.45');
insert into car (id, make, model, ,) values (681, 'Toyota', 'Avalon', '$7.74');
insert into car (id, make, model, ,) values (682, 'Mercedes-Benz', 'C-Class', '$2.18');
insert into car (id, make, model, ,) values (683, 'Cadillac', 'Escalade ESV', '$9.68');
insert into car (id, make, model, ,) values (684, 'Mitsubishi', 'Galant', '$4.51');
insert into car (id, make, model, ,) values (685, 'Mitsubishi', 'Endeavor', '$4.44');
insert into car (id, make, model, ,) values (686, 'Tesla', 'Roadster', '$3.92');
insert into car (id, make, model, ,) values (687, 'Ford', 'Ranger', '$8.67');
insert into car (id, make, model, ,) values (688, 'Volkswagen', 'Golf III', '$6.69');
insert into car (id, make, model, ,) values (689, 'Ford', 'Focus', '$8.85');
insert into car (id, make, model, ,) values (690, 'Oldsmobile', 'Cutlass Cruiser', '$6.23');
insert into car (id, make, model, ,) values (691, 'Honda', 'Civic', '$0.21');
insert into car (id, make, model, ,) values (692, 'Acura', 'TL', '$3.31');
insert into car (id, make, model, ,) values (693, 'Mazda', 'RX-8', '$7.04');
insert into car (id, make, model, ,) values (694, 'Toyota', 'Land Cruiser', '$6.98');
insert into car (id, make, model, ,) values (695, 'Suzuki', 'Reno', '$6.63');
insert into car (id, make, model, ,) values (696, 'Dodge', 'D250 Club', '$0.43');
insert into car (id, make, model, ,) values (697, 'Land Rover', 'Discovery', '$9.65');
insert into car (id, make, model, ,) values (698, 'Ford', 'Expedition', '$7.95');
insert into car (id, make, model, ,) values (699, 'Buick', 'Century', '$4.27');
insert into car (id, make, model, ,) values (700, 'GMC', 'Rally Wagon 3500', '$9.25');
insert into car (id, make, model, ,) values (701, 'Dodge', 'Ram 1500', '$7.34');
insert into car (id, make, model, ,) values (702, 'Land Rover', 'Range Rover', '$0.64');
insert into car (id, make, model, ,) values (703, 'Mercury', 'Villager', '$6.36');
insert into car (id, make, model, ,) values (704, 'Mercedes-Benz', 'S-Class', '$3.03');
insert into car (id, make, model, ,) values (705, 'Ford', 'Ranger', '$3.63');
insert into car (id, make, model, ,) values (706, 'MINI', 'Cooper', '$8.95');
insert into car (id, make, model, ,) values (707, 'Ford', 'F150', '$8.11');
insert into car (id, make, model, ,) values (708, 'Chrysler', 'PT Cruiser', '$8.34');
insert into car (id, make, model, ,) values (709, 'GMC', 'Sierra 3500', '$5.08');
insert into car (id, make, model, ,) values (710, 'Kia', 'Sorento', '$8.34');
insert into car (id, make, model, ,) values (711, 'Ford', 'Focus', '$3.23');
insert into car (id, make, model, ,) values (712, 'Nissan', 'Armada', '$5.64');
insert into car (id, make, model, ,) values (713, 'Geo', 'Tracker', '$6.86');
insert into car (id, make, model, ,) values (714, 'GMC', 'Canyon', '$0.14');
insert into car (id, make, model, ,) values (715, 'Oldsmobile', 'LSS', '$8.90');
insert into car (id, make, model, ,) values (716, 'Nissan', 'Xterra', '$2.74');
insert into car (id, make, model, ,) values (717, 'Jaguar', 'XJ', '$4.94');
insert into car (id, make, model, ,) values (718, 'Chevrolet', 'Sportvan G30', '$2.15');
insert into car (id, make, model, ,) values (719, 'Volkswagen', 'Golf', '$4.08');
insert into car (id, make, model, ,) values (720, 'Mazda', 'Mazdaspeed 3', '$7.14');
insert into car (id, make, model, ,) values (721, 'Honda', 'Civic', '$3.38');
insert into car (id, make, model, ,) values (722, 'Dodge', 'Grand Caravan', '$4.91');
insert into car (id, make, model, ,) values (723, 'BMW', '6 Series', '$8.58');
insert into car (id, make, model, ,) values (724, 'Nissan', 'Frontier', '$5.21');
insert into car (id, make, model, ,) values (725, 'Cadillac', 'Eldorado', '$1.64');
insert into car (id, make, model, ,) values (726, 'Chevrolet', 'Sportvan G30', '$9.48');
insert into car (id, make, model, ,) values (727, 'Mercedes-Benz', 'E-Class', '$0.38');
insert into car (id, make, model, ,) values (728, 'Hyundai', 'Sonata', '$2.16');
insert into car (id, make, model, ,) values (729, 'GMC', '2500 Club Coupe', '$9.13');
insert into car (id, make, model, ,) values (730, 'Buick', 'Skylark', '$0.58');
insert into car (id, make, model, ,) values (731, 'Plymouth', 'Colt Vista', '$1.62');
insert into car (id, make, model, ,) values (732, 'Mazda', 'RX-7', '$5.46');
insert into car (id, make, model, ,) values (733, 'Lamborghini', 'Murciélago LP640', '$7.09');
insert into car (id, make, model, ,) values (734, 'Volvo', 'V70', '$8.98');
insert into car (id, make, model, ,) values (735, 'Dodge', 'Grand Caravan', '$1.23');
insert into car (id, make, model, ,) values (736, 'Infiniti', 'Q', '$0.24');
insert into car (id, make, model, ,) values (737, 'Suzuki', 'Sidekick', '$3.39');
insert into car (id, make, model, ,) values (738, 'Toyota', 'Celica', '$2.07');
insert into car (id, make, model, ,) values (739, 'Land Rover', 'LR4', '$6.69');
insert into car (id, make, model, ,) values (740, 'Daihatsu', 'Rocky', '$9.11');
insert into car (id, make, model, ,) values (741, 'Infiniti', 'I', '$5.66');
insert into car (id, make, model, ,) values (742, 'Jeep', 'Compass', '$1.91');
insert into car (id, make, model, ,) values (743, 'Chevrolet', 'Express 2500', '$3.84');
insert into car (id, make, model, ,) values (744, 'Acura', 'Integra', '$10.00');
insert into car (id, make, model, ,) values (745, 'Cadillac', 'DTS', '$2.13');
insert into car (id, make, model, ,) values (746, 'Mercury', 'Grand Marquis', '$1.96');
insert into car (id, make, model, ,) values (747, 'Chevrolet', 'Express 3500', '$0.61');
insert into car (id, make, model, ,) values (748, 'Ford', 'Econoline E350', '$5.81');
insert into car (id, make, model, ,) values (749, 'BMW', '3 Series', '$6.67');
insert into car (id, make, model, ,) values (750, 'Porsche', '944', '$6.60');
insert into car (id, make, model, ,) values (751, 'Dodge', 'Ram Van B350', '$2.44');
insert into car (id, make, model, ,) values (752, 'BMW', '3 Series', '$9.36');
insert into car (id, make, model, ,) values (753, 'Ford', 'F150', '$4.33');
insert into car (id, make, model, ,) values (754, 'Plymouth', 'Acclaim', '$2.51');
insert into car (id, make, model, ,) values (755, 'GMC', '3500', '$4.26');
insert into car (id, make, model, ,) values (756, 'Nissan', 'Xterra', '$1.86');
insert into car (id, make, model, ,) values (757, 'Ford', 'Courier', '$8.76');
insert into car (id, make, model, ,) values (758, 'Infiniti', 'G37', '$4.62');
insert into car (id, make, model, ,) values (759, 'Ford', 'Expedition', '$5.47');
insert into car (id, make, model, ,) values (760, 'Buick', 'Century', '$8.58');
insert into car (id, make, model, ,) values (761, 'Nissan', 'Armada', '$0.69');
insert into car (id, make, model, ,) values (762, 'Dodge', 'Caliber', '$0.70');
insert into car (id, make, model, ,) values (763, 'Mazda', 'Miata MX-5', '$6.51');
insert into car (id, make, model, ,) values (764, 'GMC', 'Savana', '$3.79');
insert into car (id, make, model, ,) values (765, 'Lamborghini', 'Countach', '$5.49');
insert into car (id, make, model, ,) values (766, 'Dodge', 'Ram 2500', '$1.52');
insert into car (id, make, model, ,) values (767, 'Maserati', 'Spyder', '$4.32');
insert into car (id, make, model, ,) values (768, 'Subaru', 'Brat', '$4.49');
insert into car (id, make, model, ,) values (769, 'GMC', 'Rally Wagon 2500', '$3.52');
insert into car (id, make, model, ,) values (770, 'Pontiac', 'Firebird', '$7.12');
insert into car (id, make, model, ,) values (771, 'Mercedes-Benz', 'E-Class', '$1.33');
insert into car (id, make, model, ,) values (772, 'GMC', 'Sierra Hybrid', '$8.36');
insert into car (id, make, model, ,) values (773, 'Pontiac', '6000', '$7.20');
insert into car (id, make, model, ,) values (774, 'Audi', 'A6', '$9.75');
insert into car (id, make, model, ,) values (775, 'Mercury', 'Tracer', '$5.42');
insert into car (id, make, model, ,) values (776, 'Plymouth', 'Voyager', '$0.90');
insert into car (id, make, model, ,) values (777, 'Dodge', 'Grand Caravan', '$5.15');
insert into car (id, make, model, ,) values (778, 'Porsche', 'Boxster', '$8.14');
insert into car (id, make, model, ,) values (779, 'GMC', 'Savana 1500', '$4.84');
insert into car (id, make, model, ,) values (780, 'Toyota', 'Highlander', '$8.59');
insert into car (id, make, model, ,) values (781, 'Honda', 'Civic GX', '$5.80');
insert into car (id, make, model, ,) values (782, 'Mitsubishi', 'Mighty Max Macro', '$3.93');
insert into car (id, make, model, ,) values (783, 'Toyota', 'Avalon', '$6.68');
insert into car (id, make, model, ,) values (784, 'Isuzu', 'i-350', '$6.02');
insert into car (id, make, model, ,) values (785, 'Mazda', 'Familia', '$6.00');
insert into car (id, make, model, ,) values (786, 'Volvo', 'C70', '$6.41');
insert into car (id, make, model, ,) values (787, 'Chevrolet', 'Suburban 2500', '$1.01');
insert into car (id, make, model, ,) values (788, 'Ford', 'Mustang', '$0.54');
insert into car (id, make, model, ,) values (789, 'Suzuki', 'X-90', '$4.90');
insert into car (id, make, model, ,) values (790, 'Subaru', 'Impreza', '$8.31');
insert into car (id, make, model, ,) values (791, 'GMC', 'Sierra 1500', '$3.41');
insert into car (id, make, model, ,) values (792, 'Chrysler', 'Pacifica', '$1.15');
insert into car (id, make, model, ,) values (793, 'Ford', 'E-Series', '$6.64');
insert into car (id, make, model, ,) values (794, 'Lincoln', 'Continental', '$4.93');
insert into car (id, make, model, ,) values (795, 'Pontiac', 'Firebird', '$3.51');
insert into car (id, make, model, ,) values (796, 'Jaguar', 'XK Series', '$7.90');
insert into car (id, make, model, ,) values (797, 'Toyota', 'MR2', '$5.34');
insert into car (id, make, model, ,) values (798, 'Mercedes-Benz', 'SLK-Class', '$3.62');
insert into car (id, make, model, ,) values (799, 'Mitsubishi', 'Mirage', '$6.78');
insert into car (id, make, model, ,) values (800, 'Volkswagen', 'Touareg', '$2.80');
insert into car (id, make, model, ,) values (801, 'Ford', 'Freestyle', '$4.31');
insert into car (id, make, model, ,) values (802, 'Toyota', 'Solara', '$9.94');
insert into car (id, make, model, ,) values (803, 'Ford', 'Festiva', '$7.36');
insert into car (id, make, model, ,) values (804, 'Mitsubishi', 'Precis', '$0.04');
insert into car (id, make, model, ,) values (805, 'Chevrolet', 'Silverado 1500', '$4.92');
insert into car (id, make, model, ,) values (806, 'Suzuki', 'Vitara', '$9.30');
insert into car (id, make, model, ,) values (807, 'Audi', '90', '$1.57');
insert into car (id, make, model, ,) values (808, 'Nissan', 'Sentra', '$3.58');
insert into car (id, make, model, ,) values (809, 'Buick', 'Regal', '$6.71');
insert into car (id, make, model, ,) values (810, 'Dodge', 'D150 Club', '$9.50');
insert into car (id, make, model, ,) values (811, 'GMC', 'Yukon XL 1500', '$6.09');
insert into car (id, make, model, ,) values (812, 'Mazda', 'MX-5', '$7.92');
insert into car (id, make, model, ,) values (813, 'Honda', 'S2000', '$6.68');
insert into car (id, make, model, ,) values (814, 'Toyota', 'Sequoia', '$2.35');
insert into car (id, make, model, ,) values (815, 'Audi', 'S4', '$1.89');
insert into car (id, make, model, ,) values (816, 'Ford', 'Fusion', '$1.98');
insert into car (id, make, model, ,) values (817, 'Ram', 'Dakota', '$2.96');
insert into car (id, make, model, ,) values (818, 'Honda', 'Accord', '$4.58');
insert into car (id, make, model, ,) values (819, 'Mercedes-Benz', 'E-Class', '$8.15');
insert into car (id, make, model, ,) values (820, 'Mercury', 'Grand Marquis', '$0.11');
insert into car (id, make, model, ,) values (821, 'Chevrolet', 'Suburban 1500', '$2.71');
insert into car (id, make, model, ,) values (822, 'BMW', '745', '$7.03');
insert into car (id, make, model, ,) values (823, 'Ford', 'Crown Victoria', '$0.83');
insert into car (id, make, model, ,) values (824, 'Volkswagen', 'Cabriolet', '$7.05');
insert into car (id, make, model, ,) values (825, 'Isuzu', 'i-350', '$1.24');
insert into car (id, make, model, ,) values (826, 'Chevrolet', '3500', '$2.05');
insert into car (id, make, model, ,) values (827, 'Infiniti', 'G37', '$4.01');
insert into car (id, make, model, ,) values (828, 'Volkswagen', 'Touareg', '$3.29');
insert into car (id, make, model, ,) values (829, 'Pontiac', 'Bonneville', '$3.82');
insert into car (id, make, model, ,) values (830, 'Honda', 'CR-V', '$8.99');
insert into car (id, make, model, ,) values (831, 'Cadillac', 'CTS-V', '$6.96');
insert into car (id, make, model, ,) values (832, 'Mitsubishi', 'Galant', '$2.39');
insert into car (id, make, model, ,) values (833, 'Chevrolet', 'Silverado 2500', '$5.20');
insert into car (id, make, model, ,) values (834, 'Subaru', 'Legacy', '$2.93');
insert into car (id, make, model, ,) values (835, 'Lexus', 'RX', '$4.34');
insert into car (id, make, model, ,) values (836, 'Infiniti', 'QX56', '$9.28');
insert into car (id, make, model, ,) values (837, 'Mitsubishi', 'Diamante', '$8.40');
insert into car (id, make, model, ,) values (838, 'BMW', '3 Series', '$4.25');
insert into car (id, make, model, ,) values (839, 'Oldsmobile', 'Bravada', '$7.64');
insert into car (id, make, model, ,) values (840, 'Dodge', 'Colt', '$4.24');
insert into car (id, make, model, ,) values (841, 'Land Rover', 'Discovery', '$1.19');
insert into car (id, make, model, ,) values (842, 'GMC', '3500 Club Coupe', '$6.70');
insert into car (id, make, model, ,) values (843, 'Chevrolet', 'Tahoe', '$5.15');
insert into car (id, make, model, ,) values (844, 'Toyota', 'Tacoma', '$1.76');
insert into car (id, make, model, ,) values (845, 'Geo', 'Prizm', '$7.57');
insert into car (id, make, model, ,) values (846, 'Mercedes-Benz', '300E', '$8.30');
insert into car (id, make, model, ,) values (847, 'BMW', '5 Series', '$8.75');
insert into car (id, make, model, ,) values (848, 'Dodge', 'Ram 3500', '$2.31');
insert into car (id, make, model, ,) values (849, 'Ford', 'LTD Crown Victoria', '$5.50');
insert into car (id, make, model, ,) values (850, 'GMC', 'Suburban 2500', '$4.12');
insert into car (id, make, model, ,) values (851, 'Ford', 'Taurus', '$9.08');
insert into car (id, make, model, ,) values (852, 'Nissan', 'GT-R', '$0.85');
insert into car (id, make, model, ,) values (853, 'Mercedes-Benz', 'S-Class', '$9.53');
insert into car (id, make, model, ,) values (854, 'Mercedes-Benz', 'S-Class', '$3.12');
insert into car (id, make, model, ,) values (855, 'Suzuki', 'Esteem', '$0.00');
insert into car (id, make, model, ,) values (856, 'Chevrolet', 'Cavalier', '$2.58');
insert into car (id, make, model, ,) values (857, 'Oldsmobile', 'Bravada', '$5.15');
insert into car (id, make, model, ,) values (858, 'Spyker', 'C8 Spyder', '$0.36');
insert into car (id, make, model, ,) values (859, 'BMW', 'M3', '$8.45');
insert into car (id, make, model, ,) values (860, 'Bentley', 'Continental Super', '$4.34');
insert into car (id, make, model, ,) values (861, 'Lamborghini', 'Gallardo', '$6.26');
insert into car (id, make, model, ,) values (862, 'Chevrolet', 'Express 2500', '$0.92');
insert into car (id, make, model, ,) values (863, 'Buick', 'Century', '$0.48');
insert into car (id, make, model, ,) values (864, 'Chevrolet', 'Colorado', '$1.28');
insert into car (id, make, model, ,) values (865, 'Toyota', 'RAV4', '$1.54');
insert into car (id, make, model, ,) values (866, 'Volvo', 'C70', '$5.99');
insert into car (id, make, model, ,) values (867, 'Oldsmobile', 'Bravada', '$1.16');
insert into car (id, make, model, ,) values (868, 'Ford', 'Mustang', '$3.22');
insert into car (id, make, model, ,) values (869, 'Isuzu', 'Ascender', '$1.16');
insert into car (id, make, model, ,) values (870, 'Lexus', 'LX', '$9.51');
insert into car (id, make, model, ,) values (871, 'Lexus', 'GX', '$6.29');
insert into car (id, make, model, ,) values (872, 'Lincoln', 'Mark VII', '$6.31');
insert into car (id, make, model, ,) values (873, 'Dodge', 'Intrepid', '$2.70');
insert into car (id, make, model, ,) values (874, 'Subaru', 'SVX', '$2.87');
insert into car (id, make, model, ,) values (875, 'Kia', 'Sorento', '$5.97');
insert into car (id, make, model, ,) values (876, 'Toyota', 'RAV4', '$8.11');
insert into car (id, make, model, ,) values (877, 'Mazda', 'RX-7', '$5.98');
insert into car (id, make, model, ,) values (878, 'Mazda', 'MX-6', '$3.97');
insert into car (id, make, model, ,) values (879, 'Acura', 'TSX', '$9.78');
insert into car (id, make, model, ,) values (880, 'Mercedes-Benz', 'SL-Class', '$5.84');
insert into car (id, make, model, ,) values (881, 'Chevrolet', 'S10', '$2.99');
insert into car (id, make, model, ,) values (882, 'Lincoln', 'Continental', '$0.76');
insert into car (id, make, model, ,) values (883, 'Kia', 'Optima', '$2.36');
insert into car (id, make, model, ,) values (884, 'Buick', 'Century', '$8.82');
insert into car (id, make, model, ,) values (885, 'Volkswagen', 'Eurovan', '$7.83');
insert into car (id, make, model, ,) values (886, 'Toyota', '4Runner', '$1.40');
insert into car (id, make, model, ,) values (887, 'Audi', 'S6', '$0.79');
insert into car (id, make, model, ,) values (888, 'Chevrolet', 'Monza', '$4.16');
insert into car (id, make, model, ,) values (889, 'Dodge', 'Colt', '$2.67');
insert into car (id, make, model, ,) values (890, 'Mazda', 'Protege', '$3.55');
insert into car (id, make, model, ,) values (891, 'Pontiac', 'Grand Prix', '$8.69');
insert into car (id, make, model, ,) values (892, 'BMW', 'M3', '$8.26');
insert into car (id, make, model, ,) values (893, 'Chrysler', '200', '$6.41');
insert into car (id, make, model, ,) values (894, 'Porsche', '911', '$4.69');
insert into car (id, make, model, ,) values (895, 'Jaguar', 'XJ Series', '$4.54');
insert into car (id, make, model, ,) values (896, 'Ford', 'Explorer', '$2.14');
insert into car (id, make, model, ,) values (897, 'BMW', '745', '$5.32');
insert into car (id, make, model, ,) values (898, 'GMC', 'Jimmy', '$5.25');
insert into car (id, make, model, ,) values (899, 'BMW', '7 Series', '$6.86');
insert into car (id, make, model, ,) values (900, 'Hyundai', 'Tucson', '$3.92');
insert into car (id, make, model, ,) values (901, 'Lamborghini', 'Diablo', '$8.30');
insert into car (id, make, model, ,) values (902, 'Pontiac', 'LeMans', '$9.23');
insert into car (id, make, model, ,) values (903, 'Toyota', 'Ipsum', '$1.52');
insert into car (id, make, model, ,) values (904, 'Aptera', '2e', '$2.89');
insert into car (id, make, model, ,) values (905, 'Kia', 'Amanti', '$5.02');
insert into car (id, make, model, ,) values (906, 'Chevrolet', 'Traverse', '$4.26');
insert into car (id, make, model, ,) values (907, 'Buick', 'Century', '$7.78');
insert into car (id, make, model, ,) values (908, 'Mercury', 'Grand Marquis', '$7.72');
insert into car (id, make, model, ,) values (909, 'Pontiac', 'GTO', '$2.73');
insert into car (id, make, model, ,) values (910, 'Mercedes-Benz', 'R-Class', '$0.24');
insert into car (id, make, model, ,) values (911, 'Mercedes-Benz', 'C-Class', '$5.01');
insert into car (id, make, model, ,) values (912, 'Mitsubishi', 'Starion', '$7.28');
insert into car (id, make, model, ,) values (913, 'Lamborghini', 'Diablo', '$0.47');
insert into car (id, make, model, ,) values (914, 'GMC', 'Sierra 1500', '$1.67');
insert into car (id, make, model, ,) values (915, 'Ford', 'F-Series', '$2.83');
insert into car (id, make, model, ,) values (916, 'Nissan', 'Sentra', '$7.56');
insert into car (id, make, model, ,) values (917, 'Pontiac', 'G5', '$4.78');
insert into car (id, make, model, ,) values (918, 'Saab', '900', '$7.34');
insert into car (id, make, model, ,) values (919, 'Volkswagen', 'Fox', '$9.91');
insert into car (id, make, model, ,) values (920, 'Volkswagen', 'Touareg', '$2.92');
insert into car (id, make, model, ,) values (921, 'Mazda', 'Miata MX-5', '$0.98');
insert into car (id, make, model, ,) values (922, 'Chrysler', 'Town & Country', '$5.23');
insert into car (id, make, model, ,) values (923, 'Dodge', 'Challenger', '$2.42');
insert into car (id, make, model, ,) values (924, 'Nissan', '300ZX', '$8.47');
insert into car (id, make, model, ,) values (925, 'Porsche', '911', '$9.16');
insert into car (id, make, model, ,) values (926, 'Dodge', 'Ram 1500', '$1.25');
insert into car (id, make, model, ,) values (927, 'Lamborghini', 'Diablo', '$5.82');
insert into car (id, make, model, ,) values (928, 'Toyota', 'TundraMax', '$9.85');
insert into car (id, make, model, ,) values (929, 'Toyota', 'T100', '$0.05');
insert into car (id, make, model, ,) values (930, 'Infiniti', 'G', '$1.40');
insert into car (id, make, model, ,) values (931, 'Mazda', 'CX-7', '$6.72');
insert into car (id, make, model, ,) values (932, 'Pontiac', 'Bonneville', '$4.32');
insert into car (id, make, model, ,) values (933, 'Mitsubishi', 'Diamante', '$8.56');
insert into car (id, make, model, ,) values (934, 'Mercury', 'Cougar', '$9.05');
insert into car (id, make, model, ,) values (935, 'Honda', 'Passport', '$6.13');
insert into car (id, make, model, ,) values (936, 'GMC', '2500 Club Coupe', '$5.07');
insert into car (id, make, model, ,) values (937, 'Ferrari', 'F430', '$7.18');
insert into car (id, make, model, ,) values (938, 'Mitsubishi', 'Pajero', '$5.84');
insert into car (id, make, model, ,) values (939, 'Mazda', 'Tribute', '$5.41');
insert into car (id, make, model, ,) values (940, 'Plymouth', 'Fury', '$0.24');
insert into car (id, make, model, ,) values (941, 'Ford', 'F250', '$3.76');
insert into car (id, make, model, ,) values (942, 'Isuzu', 'Rodeo', '$6.54');
insert into car (id, make, model, ,) values (943, 'Land Rover', 'Range Rover', '$2.41');
insert into car (id, make, model, ,) values (944, 'Nissan', 'Pathfinder', '$9.38');
insert into car (id, make, model, ,) values (945, 'Mercury', 'Mountaineer', '$0.98');
insert into car (id, make, model, ,) values (946, 'Ford', 'Escape', '$7.39');
insert into car (id, make, model, ,) values (947, 'Chevrolet', 'Corvette', '$4.69');
insert into car (id, make, model, ,) values (948, 'Nissan', 'Titan', '$6.08');
insert into car (id, make, model, ,) values (949, 'Volvo', 'V50', '$0.88');
insert into car (id, make, model, ,) values (950, 'Ford', 'Mustang', '$3.11');
insert into car (id, make, model, ,) values (951, 'Mitsubishi', 'Pajero', '$6.42');
insert into car (id, make, model, ,) values (952, 'Volkswagen', 'R32', '$1.03');
insert into car (id, make, model, ,) values (953, 'Mitsubishi', 'Endeavor', '$3.37');
insert into car (id, make, model, ,) values (954, 'Volvo', 'XC90', '$0.66');
insert into car (id, make, model, ,) values (955, 'Toyota', 'Sequoia', '$4.59');
insert into car (id, make, model, ,) values (956, 'Ford', 'F150', '$6.25');
insert into car (id, make, model, ,) values (957, 'Mitsubishi', 'Montero', '$9.63');
insert into car (id, make, model, ,) values (958, 'Dodge', 'Ram 3500', '$2.59');
insert into car (id, make, model, ,) values (959, 'Hyundai', 'Azera', '$2.06');
insert into car (id, make, model, ,) values (960, 'Honda', 'Accord', '$8.32');
insert into car (id, make, model, ,) values (961, 'Chevrolet', 'Malibu', '$0.30');
insert into car (id, make, model, ,) values (962, 'Acura', 'NSX', '$4.35');
insert into car (id, make, model, ,) values (963, 'Mazda', 'Miata MX-5', '$4.63');
insert into car (id, make, model, ,) values (964, 'BMW', 'X5', '$3.31');
insert into car (id, make, model, ,) values (965, 'Mercedes-Benz', 'W201', '$3.70');
insert into car (id, make, model, ,) values (966, 'Subaru', 'Alcyone SVX', '$2.92');
insert into car (id, make, model, ,) values (967, 'Volkswagen', 'Eos', '$7.12');
insert into car (id, make, model, ,) values (968, 'Volvo', 'C70', '$3.50');
insert into car (id, make, model, ,) values (969, 'Mercedes-Benz', 'SL-Class', '$3.72');
insert into car (id, make, model, ,) values (970, 'Lamborghini', 'Countach', '$6.57');
insert into car (id, make, model, ,) values (971, 'Lincoln', 'Navigator L', '$1.80');
insert into car (id, make, model, ,) values (972, 'Ford', 'Econoline E350', '$0.36');
insert into car (id, make, model, ,) values (973, 'GMC', 'Sierra 1500', '$9.73');
insert into car (id, make, model, ,) values (974, 'BMW', '545', '$8.39');
insert into car (id, make, model, ,) values (975, 'Subaru', 'Tribeca', '$3.07');
insert into car (id, make, model, ,) values (976, 'Ford', 'Taurus X', '$1.57');
insert into car (id, make, model, ,) values (977, 'GMC', 'Yukon XL 1500', '$7.22');
insert into car (id, make, model, ,) values (978, 'Ford', 'Escape', '$7.57');
insert into car (id, make, model, ,) values (979, 'Chevrolet', 'Avalanche', '$3.85');
insert into car (id, make, model, ,) values (980, 'Saab', '9-3', '$6.92');
insert into car (id, make, model, ,) values (981, 'Subaru', 'Baja', '$9.52');
insert into car (id, make, model, ,) values (982, 'Dodge', 'Ram', '$8.33');
insert into car (id, make, model, ,) values (983, 'Lincoln', 'Aviator', '$9.25');
insert into car (id, make, model, ,) values (984, 'Ford', 'Thunderbird', '$5.20');
insert into car (id, make, model, ,) values (985, 'Nissan', 'Leaf', '$2.29');
insert into car (id, make, model, ,) values (986, 'GMC', 'Savana 3500', '$4.59');
insert into car (id, make, model, ,) values (987, 'Saab', '9-5', '$5.34');
insert into car (id, make, model, ,) values (988, 'Pontiac', 'Bonneville', '$6.81');
insert into car (id, make, model, ,) values (989, 'GMC', 'Sonoma', '$7.74');
insert into car (id, make, model, ,) values (990, 'Jaguar', 'XJ Series', '$1.05');
insert into car (id, make, model, ,) values (991, 'Infiniti', 'G', '$5.60');
insert into car (id, make, model, ,) values (992, 'Toyota', 'Sienna', '$5.31');
insert into car (id, make, model, ,) values (993, 'Ford', 'Econoline E250', '$0.65');
insert into car (id, make, model, ,) values (994, 'GMC', 'Rally Wagon G3500', '$1.48');
insert into car (id, make, model, ,) values (995, 'BMW', 'X5', '$3.68');
insert into car (id, make, model, ,) values (996, 'Ford', 'Probe', '$4.17');
insert into car (id, make, model, ,) values (997, 'GMC', 'Envoy', '$1.48');
insert into car (id, make, model, ,) values (998, 'Toyota', 'Camry Hybrid', '$2.88');
insert into car (id, make, model, ,) values (999, 'BMW', 'M Roadster', '$5.13');
insert into car (id, make, model, ,) values (1000, 'Chrysler', 'LHS', '$8.74');
